### ISSUE TITLE
先 star 为敬，项目有没有对应的技术博客做介绍

### ISSUE THREAD

**Issue by 13120241790** [Knight-ZXW/CpuProfiler#1]
先 star 为敬，项目有没有对应的技术博客做介绍

**Comment by Knight-ZXW** [comment]
这个仓库一直没更新。后续有时间补上

博客介绍: https://juejin.cn/post/7135034198158475300

另一个项目我已经实现了完整的代码 https://github.com/Knight-ZXW/moonlight-apm-android/blob/master/apm/src/main/java/com/knightboost/apm/cpu/monitor/CpuUsageMonitor.kt
